version: "3.8"
services:
   backend:
       build: ./example-backend
       ports:
            - 8080:8080
       environment:
           REDIS_HOST: redis
           POSTGRES_HOST: postgres
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DATABASE: postgres
       depends_on:
            - redis
            - postgres
   frontend:
       build: ./example-frontend
       ports:
            - 5000:5000
   redis:
       container_name: redisache
       image: redis
       restart: unless-stopped
   postgres:
       container_name: pg
       image: postgres
       environment:
           POSTGRES_HOST: postgres
           POSTGRES_USER: postgres
           POSTGRES_PASSWORD: postgres
           POSTGRES_DATABASE: postgres      
    
 
