version: "3.8"
services:
   backend:
       build: ./example-backend
       ports:
            - 8080:8080
       environment:
           REDIS_HOST: redis
       depends_on:
            - redis
   frontend:
       build: ./example-frontend
       ports:
            - 5000:5000
   redis:
       container_name: redis-cache
       image: redis
       restart: unless-stopped
 
